using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{
    class Program
    {
        static void Main(string[] args)
        {

            //Problem 1: Find the sum of all the multiples of 3 or 5 below 1000.
            int i = 0; //Counter
            int sum = 0;
            while (i < 1000)
            {
                if (i % 3 == 0 || i % 5 == 0) //Checking if the current number is a multiple of 3 or 5
                {
                    sum += i;
                }
                i++;
            }
            Console.WriteLine($"Problem 1: sum is {sum}");

            //Problem 2
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            int prev = 0;//keep previous term
            int current = 1;//keep current term
            int total = 0;// sum of prev and current
            int sumOfEven = 0;//to keep 
            while (current < 4000000)
            {
                if (current % 2 == 0)
                {
                    sumOfEven += total;
                }
                total = prev + current;
                prev = current;
                current = total;
            }
            Console.WriteLine($"Problem 2: The total is: {sumOfEven}");

        }
    }
}
